
export const publicRoutes = [
    {
        id:1,
        title:'Home',
        path:'/'
    },
    {
        id:2,
        title:'About',
        path:'/about'
    },
    {
        id:3,
        title:'Explore',
        path:'/explore'
    },
    {
        id:4,
        title:'Collections',
        path:'/collections'
    },
    {
        id:5,
        title:'Blog',
        path:'/blogs'
    },
    {
        id:6,
        title:'Contact',
        path:'/contact'
    },
]